### ISSUE TITLE
builtinの挙動をbashと合わせる (対応の必要ない可能性あり)

### ISSUE THREAD

**Issue by kose-yusuke** [kose-yusuke/minishell#100]
乱雑な状態ですみません... 一旦issueとしてあげておきます.

- exit ' 3 'などexit コマンドの引数のスペースは無視。 exit LONG_MAX以上の数値を入れるとnumeric argument requiredが出るはず。( #108 )

- exitで親にステータスを返せてるか確認。exit | exitでexitするはずなのにしない.  [動作確認の結果](https://github.com/kose-yusuke/minishell/issues/100#issuecomment-2387680982)

- echo - -n の出力が間違ってそう. [動作確認の結果](https://github.com/kose-yusuke/minishell/issues/100#issuecomment-2387683533)
koseki.yusuke@MacBook-Air-29 [~/work/Lab/GLAFS] % echo - -n
-n
minishell$ echo - -n
- -n

- export PATH=$PATH:$PWDで何故かPATHが$PWDだけ残って他全部消える. これは確認必須かも. ( #101 )

- $Aでsyntax error ( #103 )
何も実行しないのが正解らしい。

- echo -nnnnannnna -nnnnn -n helloなどの挙動がおかしいかも。( #105 )
bash-3.2$ echo -nnnnannnna -nnnnn -n hello
-nnnnannnna -nnnnn -n hello
minishell$ echo -nnnnannnna -nnnnn -n hello
-nnnnn -n hellominishell$

**Comment by skitheom** [comment]
### `exit | exit` について
確認したところ私の環境だと、`exit | exit`で親プロセスは終了しないみたいです
```bash
bash-3.2$ exit | exit
bash-3.2$ echo $?
0
bash-3.2$
```
```bash
minishell$ exit | exit
minishell$ echo $?
0
minishell$
```

**Comment by skitheom** [comment]
#### `echo - -n` および `echo --n` について
確認したところ、私の環境だと以下のとおり動作していました
```bash
bash-3.2$ echo - -n
- -n
bash-3.2$ echo $?
0
bash-3.2$ echo --n
--n
bash-3.2$ echo $?
0
bash-3.2$
```
```bash
minishell$ echo - -n
- -n
minishell$ echo $?
0
minishell$ echo --n
--n
minishell$ echo $?
0
minishell$
```

**Comment by kose-yusuke** [comment]
すみません、、こちらexit | exitとechoについては, zshで試したものを勘違いして載せてしまっていたみたいです...僕のbash環境でもきたはらさんと同様の結果が得られました. ご確認いただきありがとうございます🙇‍♀️

**Comment by skitheom** [comment]
すべて確認できました
